import smtplib
from datetime import datetime
from email.header import Header
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

import markdown as md

from app.ai.weekly_planner import generate_weekly_plan
from app.config import load_settings
from app.database.connection import get_connection
from app.utils_logger import setup_logger


logger = setup_logger("email_sender")

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:#F4F5F7;
             font-family:'Segoe UI', Arial, sans-serif; color:#1A1A2E;">
  <div style="max-width:680px; margin:0 auto; padding:24px;">
    <div style="background:#405DE6; border-radius:12px 12px 0 0;
                padding:28px 32px; color:#ffffff;">
      <div style="font-size:1.5rem; font-weight:700;">📊 InstaSight</div>
      <div style="font-size:0.95rem; opacity:0.9; margin-top:4px;">
        Weekly Instagram Growth Plan
      </div>
      <div style="font-size:0.9rem; margin-top:12px;
                  background:rgba(255,255,255,0.15); display:inline-block;
                  padding:6px 12px; border-radius:6px;">
        @{username} &nbsp;·&nbsp; {week_start} → {week_end}
      </div>
    </div>
    <div style="background:#ffffff; padding:32px;
                border:1px solid #E9ECEF; border-top:none; line-height:1.6;">
      {body}
    </div>
    <div style="background:#F8F9FA; border-radius:0 0 12px 12px;
                padding:18px 32px; border:1px solid #E9ECEF; border-top:none;
                color:#6C757D; font-size:0.8rem; text-align:center;">
      Generated by InstaSight | Powered by AI
    </div>
  </div>
</body>
</html>
"""


def _render_html(plan: Dict[str, Any]) -> str:
    body_html = md.markdown(
        plan["plan"],
        extensions=["extra", "sane_lists", "nl2br"],
    )
    return _HTML_TEMPLATE.format(
        username=plan["username"],
        week_start=plan["week_start"],
        week_end=plan["week_end"],
        body=body_html,
    )


def send_weekly_plan_email(
    account_id: str,
    recipient_email: str,
    plan: Optional[Dict[str, Any]] = None,
) -> bool:
    """
    Generate (or reuse) the weekly plan and email it via Gmail SMTP.

    Returns True on success, False on failure. A pre-generated `plan` dict
    (as returned by generate_weekly_plan) can be passed to avoid a second
    Claude API call.
    """
    settings = load_settings()

    if not settings.gmail_address or not settings.gmail_app_password:
        logger.error(
            "Gmail credentials missing. Set GMAIL_ADDRESS and GMAIL_APP_PASSWORD in .env"
        )
        return False

    try:
        if plan is None:
            plan = generate_weekly_plan(account_id)

        username = plan["username"]
        subject = (
            f"📊 Weekly Instagram Growth Plan — @{username} | "
            f"{plan['week_start']} to {plan['week_end']}"
        )

        message = MIMEMultipart("alternative")
        message["Subject"] = Header(subject, "utf-8")
        message["From"] = settings.gmail_address
        message["To"] = recipient_email
        message.attach(MIMEText(plan["plan"], "plain", "utf-8"))
        message.attach(MIMEText(_render_html(plan), "html", "utf-8"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(settings.gmail_address, settings.gmail_app_password)
            server.send_message(message)

        logger.info(
            "Weekly plan email sent to %s for @%s",
            recipient_email,
            username,
        )
        return True
    except Exception as exc:  # noqa: BLE001 - report any send failure as False
        logger.error(
            "Failed to send weekly plan email to %s: %s",
            recipient_email,
            exc,
        )
        return False


_ALERT_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:#F4F5F7;
             font-family:'Segoe UI', Arial, sans-serif; color:#1A1A2E;">
  <div style="max-width:680px; margin:0 auto; padding:24px;">
    <div style="background:#1A1A2E; border-radius:12px 12px 0 0;
                padding:28px 32px; color:#ffffff;">
      <div style="font-size:1.5rem; font-weight:700;">📊 InstaSight Performance Alert</div>
      <div style="font-size:0.9rem; margin-top:12px;
                  background:rgba(255,255,255,0.15); display:inline-block;
                  padding:6px 12px; border-radius:6px;">
        @{username} &nbsp;·&nbsp; {date}
      </div>
    </div>
    <div style="background:#ffffff; padding:32px;
                border:1px solid #E9ECEF; border-top:none; line-height:1.6;">
      {body}
    </div>
    <div style="background:#F8F9FA; border-radius:0 0 12px 12px;
                padding:18px 32px; border:1px solid #E9ECEF; border-top:none;
                color:#6C757D; font-size:0.8rem; text-align:center;">
      InstaSight Automated Monitoring | {timestamp}
    </div>
  </div>
</body>
</html>
"""


def _alert_badge_color(alert_type: str) -> str:
    if alert_type in ("engagement_drop", "posting_inactivity"):
        return "#DC3545"
    if alert_type == "engagement_spike":
        return "#28A745"
    return "#6C757D"


def _get_username(account_id: str) -> str:
    try:
        with get_connection() as conn:
            row = conn.execute(
                "SELECT username FROM accounts WHERE id = ?",
                (account_id,),
            ).fetchone()
        if row and row["username"]:
            return row["username"]
    except Exception:  # noqa: BLE001 - fall back to id if lookup fails
        pass
    return account_id


def _render_alert_html(username: str, alerts: List[Dict[str, Any]]) -> str:
    cards = []
    for alert in alerts:
        color = _alert_badge_color(alert["alert_type"])
        label = alert["alert_type"].replace("_", " ").title()
        previous = alert.get("metric_previous")
        current = alert.get("metric_value")
        cards.append(
            f"""
            <div style="border:1px solid #E9ECEF; border-radius:10px;
                        padding:16px 18px; margin-bottom:14px;">
              <span style="background:{color}; color:#ffffff; font-size:0.72rem;
                           font-weight:700; padding:4px 12px; border-radius:20px;
                           text-transform:uppercase; letter-spacing:0.04em;">
                {label}
              </span>
              <p style="margin:14px 0 8px 0; color:#1A1A2E;">{alert['message']}</p>
              <div style="font-size:0.85rem; color:#6C757D;">
                Metric change: {previous}% → {current}%
              </div>
            </div>
            """
        )
    body = "\n".join(cards)
    now = datetime.now()
    return _ALERT_HTML_TEMPLATE.format(
        username=username,
        date=now.strftime("%Y-%m-%d"),
        timestamp=now.replace(microsecond=0).isoformat(),
        body=body,
    )


def _render_alert_text(username: str, alerts: List[Dict[str, Any]]) -> str:
    lines = [f"InstaSight Performance Alert for @{username}", ""]
    for alert in alerts:
        label = alert["alert_type"].replace("_", " ").title()
        lines.append(f"[{label}] {alert['message']}")
        lines.append(
            f"   Metric change: {alert.get('metric_previous')}% -> "
            f"{alert.get('metric_value')}%"
        )
        lines.append("")
    lines.append(f"InstaSight Automated Monitoring | {datetime.now().isoformat()}")
    return "\n".join(lines)


def send_alert_email(account_id: str, alerts: List[Dict[str, Any]]) -> bool:
    """
    Email a performance-alert digest to the configured Gmail address.

    Returns True on success, False on failure (including no alerts to send).
    """
    settings = load_settings()

    if not settings.gmail_address or not settings.gmail_app_password:
        logger.error(
            "Gmail credentials missing. Set GMAIL_ADDRESS and GMAIL_APP_PASSWORD in .env"
        )
        return False

    if not alerts:
        logger.info("No alerts to email for %s; skipping.", account_id)
        return False

    recipient_email = settings.gmail_address

    try:
        username = _get_username(account_id)
        subject = f"⚠️ InstaSight Alert — @{username} | {datetime.now().strftime('%Y-%m-%d')}"

        message = MIMEMultipart("alternative")
        message["Subject"] = Header(subject, "utf-8")
        message["From"] = settings.gmail_address
        message["To"] = recipient_email
        message.attach(MIMEText(_render_alert_text(username, alerts), "plain", "utf-8"))
        message.attach(MIMEText(_render_alert_html(username, alerts), "html", "utf-8"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(settings.gmail_address, settings.gmail_app_password)
            server.send_message(message)

        logger.info(
            "Alert email sent to %s for @%s (%s alerts)",
            recipient_email,
            username,
            len(alerts),
        )
        return True
    except Exception as exc:  # noqa: BLE001 - report any send failure as False
        logger.error(
            "Failed to send alert email for %s: %s",
            account_id,
            exc,
        )
        return False
